### ISSUE TITLE
Error updating head reference while cloning

### ISSUE THREAD

**Issue by sirnewton01** [driusan/go-git#5]
When I try to clone a specific git repository I am getting an error updating head reference the following message:
"open .git/refs/heads/refs/heads/master: '.git/refs/heads/refs' does not exist"

The source of the error appears to come from cmd/reset.go around here:
https://github.com/driusan/go-git/blob/master/cmd/reset.go#L59

The branch name that comes back from c.GetHeadBranch() is "refs/heads/master," which is being appended to "refs/heads" creating a path that doesn't exist within the git repository.

**Comment by driusan** [comment]
That's odd, I specifically remember fixing that. I'll have to check if it was on a WIP branch when when I get home.

In the meantime, try changing that line to:

`err := c.GitDir.WriteFile(git.File(branchName.String()),`

Branch is a type of RefSpec, and as you pointed out, the refspec already contains the "refs/heads" portion of the filename.

**Comment by driusan** [comment]
(Actually I just quickly reproduced it and fixed it myself 3410cd9..)
